---
title: "Bem-vinda(o) ao Blog da Regional"
description: |
  Bem-vinda(o) ao Blog da Regional.
author:
  - name: Sandra Guimarães 
    url: 
date: 01-08-2021
categories:
  - Boas-vindas
output:
  distill::distill_article:
    self_contained: false
---


Prezados (as) Prefeitos (as), Gestores (as) e Técnicos (as)
Bem-vindos ao Blog da Diretoria Regional da SEDESE Divinópolis.

Este canal de comunicação tem o objetivo de partilhar dados, normas, leis, estudos e
informações relevantes para a implementação e efetividade das políticas públicas
nos municípios, especialmente, as sociais.

A Regional existe para apoiar e dar suporte técnico aos (às) gestores (as) municipais e
contribuir na elaboração e análise das políticas públicas em desenvolvimento.
Para cumprir suas atribuições, a Regional conta com uma equipe formada por
analistas, assistentes e especialistas nas áreas da Administração Pública, Serviço
Social, Psicologia, Sociologia e gestão do SUAS.

Sandra Guimarães, diretora regional.
